# url: https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/
---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    colored:
        (): 'colorlog.ColoredFormatter'
        log_colors:
          'DEBUG': 'cyan'
          'INFO': 'green'
          'WARNING': 'yellow'
          'ERROR': 'red'
          'CRITICAL': 'red'
        datefmt: "%H:%M:%S"
        reset: True
        format: "%(asctime)-12s%(log_color)s%(levelname)-8s%(reset)s %(blue)s%(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
#        formatter: simple
        formatter: colored
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: colored
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: colored
        filename: errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    my_module:
        level: ERROR
        handlers: [console]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
